#########################
# Imports:
import time, requests
from .assembly_key import ASSEMBLY_AI_API_KEY
# Constants:
upload_endpoint = 'https://api.assemblyai.com/v2/upload'
transcription_endpoint = 'https://api.assemblyai.com/v2/transcript'
headers = {'authorization': ASSEMBLY_AI_API_KEY}
#########################

#########################
# Upload a file
# Desc: uploads a select file to Assembly AI endpoint
# Params: file path for your audio file
# Return: the assembly AI url of where your file lives
# Dependant on: N.A.
#########################
def upload(file_path: str):
    def ReadFile(file_path, chunk_size=5242880): # chunking size of ~5 Megabytes, defined by Assembly AI
        with open(file_path, 'rb') as _file:
            while True:
                data = _file.read(chunk_size)
                if not data:
                    break
                yield data
    print('Uploading {} to Assembly AI!'.format(file_path))
    # post request for Assembly AI's endpoint
    # this will return a link of the address of where your audio file lives
    response = requests.post(upload_endpoint, headers=headers, data=ReadFile(file_path))

    # printing the full json object
    audio_url = response.json()['upload_url']
    if(audio_url):
        print('Audio uploaded to Assembly AI!')
    else:
        print('There was an issue uploading your file to Assembly AI :(')
    return audio_url

#########################
# Transcribe
# Desc: fetched the specific job Id from the Assembly Ai endpoint
# Params: Assembly AI url for the file
# Return: transcript_id
# Dependant on: N.A.
#########################
def transcribe(audio_url: str):
    audio_intel = { 
        "audio_url": audio_url,
        "speaker_labels": True, # lets you know which person is speaking in a recording
        "language_code": 'en_us', # specifies the spoken language, not needed but makes the estimates more accurate
        # "redact_pii": True, # masks personal information from the api response
    }
    transcript_response = requests.post(transcription_endpoint, json=audio_intel, headers=headers)
    transcript_id = transcript_response.json()['id']
    return transcript_id

#########################
# Perform Poll
# Desc: make get request to the api, wont always return a val, the api may be 'thinking'
# Params: transcript_id 
# Return: a large object full of data generated by assembly AI
# Dependant on: N.A.
#########################
def performPoll(transcript_id: str):
    polling_endpoint = transcription_endpoint + '/' + transcript_id
    polling_response = requests.get(polling_endpoint, headers=headers)
    return polling_response.json()

#########################
# Get Assembly AI Data i.e. speech-to-TEXT, Bread and butter Fn()
# Desc: performs all the logic to post a file and get data
# Params: file path of your audio file
# Return: Data provided by the API
# Dependant on: transcribe(), performPoll()
#########################
def getAssemblyAIData(file_name: str, audio_path='data/audio/'):
    full_path = audio_path + file_name
    audio_url = upload(full_path)
    transcript_id = transcribe(audio_url)
    while True:
        data = performPoll(transcript_id)
        if data['status'] == 'completed':
            print('Fetched Data From Assembly AI!')
            parsed_data = {
                'audio_duration': data['audio_duration'],
                'utterances': data['utterances'],
                'text': data['text'],
                'words': data['words'],
                }
            return parsed_data
        elif data['status'] == 'error':
            print('Error Fetching From Assembly AI: '+ data['error'])
            return data

        print('Waiting 5s, Assembly AI is Thinking...')
        time.sleep(5) 
